# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_add_percentage', models.FloatField(default=0.0001)),
                ('sign_least_point', models.IntegerField(default=2000)),
                ('currency', models.CharField(default='\u6d3b\u8dc3\u5ea6', max_length=20)),
                ('talk_point', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20)),
                ('group_qq', models.CharField(max_length=20)),
                ('point', models.TextField(default=b'0')),
                ('sign_continuous', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('add_point', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupUser')),
            ],
        ),
        migrations.CreateModel(
            name='TransferPointRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_point_record', to='group.GroupUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupUser')),
            ],
        ),
    ]
