# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupuser_total_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupglobalsetting',
            name='group2private_point_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='groupglobalsetting',
            name='private2group_point_percentage',
            field=models.IntegerField(default=9),
        ),
    ]
