# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nick', models.CharField(max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('qq', models.CharField(max_length=15, unique=True)),
                ('point', models.TextField(default=b'0')),
                ('clear_point_chance', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
