# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('add_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RpgGlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_up_price', models.IntegerField(default=2)),
                ('level_up_experience', models.IntegerField(default=20)),
                ('level_up_price_experience', models.IntegerField(default=3)),
                ('level_up_attack', models.IntegerField(default=3)),
                ('level_up_defensive', models.IntegerField(default=3)),
                ('level_up_health', models.IntegerField(default=3)),
                ('leveling_today_count', models.IntegerField(default=10)),
                ('level_map_step', models.IntegerField(default=10)),
                ('map_x_start', models.IntegerField(default=-1000)),
                ('map_x_end', models.IntegerField(default=1000)),
                ('map_y_start', models.IntegerField(default=-1000)),
                ('map_y_end', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RpgGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('price_experience', models.IntegerField(blank=True, default=1, null=True)),
                ('min_attack', models.IntegerField(blank=True, default=1, null=True)),
                ('max_attack', models.IntegerField(blank=True, default=3, null=True)),
                ('defensive', models.IntegerField(blank=True, default=1, null=True)),
                ('health', models.IntegerField(blank=True, default=10, null=True)),
                ('date_max_use', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpgGoodsUseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RpgGoods')),
            ],
        ),
        migrations.CreateModel(
            name='RpgMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('x_start', models.IntegerField()),
                ('x_end', models.IntegerField()),
                ('y_start', models.IntegerField()),
                ('y_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RpgPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('price_experience', models.IntegerField(blank=True, default=1, null=True)),
                ('min_attack', models.IntegerField(blank=True, default=1, null=True)),
                ('max_attack', models.IntegerField(blank=True, default=3, null=True)),
                ('defensive', models.IntegerField(blank=True, default=1, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=10)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('goods_use_records', models.ManyToManyField(blank=True, to='rpg.RpgGoodsUseRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RpgProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RpgSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.TextField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RpgSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('price_experience', models.IntegerField(blank=True, default=1, null=True)),
                ('min_attack', models.IntegerField(blank=True, default=1, null=True)),
                ('max_attack', models.IntegerField(blank=True, default=3, null=True)),
                ('defensive', models.IntegerField(blank=True, default=1, null=True)),
                ('health', models.IntegerField(blank=True, default=10, null=True)),
                ('date_max_use', models.IntegerField(default=1)),
                ('say', models.ManyToManyField(to='rpg.RpgSay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rpgperson',
            name='says',
            field=models.ManyToManyField(blank=True, to='rpg.RpgSay'),
        ),
        migrations.AddField(
            model_name='rpgperson',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levelingrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RpgPerson'),
        ),
    ]
