name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2
    - name: Copy code to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{secrets.PORT}}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
#        key: ${{ secrets.SSH_KEY }}
        source: "." # 代码所在目录
        target: "/home/linyuchen/qqrobot-plugin/" # 代码目标路径
    - name: Restart Python server
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "/home/linyuchen/qqrobot-plugin/start.sh